services:
  client-prod:
    build: 
      context: ./client
      args:
        VITE_DEFAULT_LANG: "ru"
    ports:
      - 5173:5173
    environment: 
      NGINX_PORT: 5173 
    depends_on:
      - server-prod
    networks:
      - public
  server-prod:
    build:
      context: ./server
      target: build
    environment:
      NODE_ENV: production
      SERVER_PORT: 3000
    ports:
      - 3000:3000
    networks:
      - public
networks:
  public: