services:
  client:
    build: 
      context: ./client
    ports:
      - 5173:5173
    environment: 
      NGINX_PORT: 5173 
    depends_on:
      - server
    networks:
      - public
  server:
    build:
      context: server
      target: build
    environment:
      NODE_ENV: production
      SERVER_PORT: 3000
    ports:
      - 3000:3000
    networks:
      - public
networks:
  public: